sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: '12'
      script: npm run pretest
      env: CI=pretest 12
    - node_js: '12'
      script: npm run test-only
      env: CI=tests 12
    - node_js: '11'
      script: npm run test-only
      env: CI=tests 11
    - node_js: '10'
      script: npm run test-only
      env: CI=tests 10
    - node_js: '9'
      script: npm run test-only
      env: CI=tests 9
    - node_js: '8'
      script: npm run test-only
      env: CI=tests 8

before_install:
  - npm install -g npm@latest

install:
  - npm ci

after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi
