sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: "14"
      script: npm run pretest
      env: CI=pretest 14
    - node_js: "14"
      script: npm run test-only
      env: CI=tests 14
    - node_js: "12"
      script: npm run test-only
      env: CI=tests 12

before_install:
  - npm install -g npm@latest

install:
  - npm ci

after_success:
  - if [ "$CI" = "coverage" ]; then cat ./.coverage/lcov.info | ./node_modules/.bin/coveralls; fi
